// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOxDbTHzL_prhrFZM74xGwykSd2O9EtU',
    appId: '1:530069479888:android:86505c8e866fe4d4fa59d5',
    messagingSenderId: '530069479888',
    projectId: 'tictactoe-firebase-4dfe5',
    storageBucket: 'tictactoe-firebase-4dfe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAelvZNbyoKroFb22rLvgnpAIQOQ8OG6aY',
    appId: '1:530069479888:ios:fbd5ba20c1a57ab2fa59d5',
    messagingSenderId: '530069479888',
    projectId: 'tictactoe-firebase-4dfe5',
    storageBucket: 'tictactoe-firebase-4dfe5.firebasestorage.app',
    androidClientId: '530069479888-iir57bg3nl3r1bivt62igsk8o3irt7vi.apps.googleusercontent.com',
    iosClientId: '530069479888-lcjmslau8p87ig4vo55na4em0h71pu95.apps.googleusercontent.com',
    iosBundleId: 'com.example.tictactoeFirebase',
  );
}
